################################################
## Integrations / Homeassistant
##############################################
homeassistant:
  # Lets me customize individual entities
  customize: !include_dir_merge_named ../customizations/entities
  # customize: !include ../customize.yaml
  # Lets me custimize all entities in a domain
  customize_domain: !include_dir_merge_named ../customizations/domains

  # Lets me custimize entities based on a matching pattern
  customize_glob: !include_dir_merge_named ../customizations/globs
